#!/usr/bin/env bash
set -x
set -e

git submodule init
git submodule update

find repos/kiguino/arduino/libraries -depth 1 -type d -exec ln -nfs ../{} libraries/ \;

cd libraries
  ln -nfs ../repos/SmartMatrix/src SmartMatrix
  ln -nfs ../repos/librgb/librgb RGBColor
cd -
